### ISSUE TITLE
1.21 Unexpected Error // Wrong Version // Crash

### ISSUE THREAD

**Issue by makumaku1974** [kd8lvt/exclusionzone#2]
![Screenshot 2024-06-22 164731](https://github.com/kd8lvt/exclusionzone/assets/129804277/c2ff69b3-ad1a-4f67-beef-b4bb6e356660)

**Comment by kd8lvt** [comment]
Huh. Would ya look at that. I forgot to change the accepted versions 🤦 
Should be fixed in a moment, sorry about that!

**Comment by kd8lvt** [comment]
Closed by latest release (1.0.1-1.21)
Again, sorry about that - not sure how it slipped under the radar. I _did_ test that it loaded before releasing 1.21 lol
